[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "26KdmFpYTmAauE1JT3sUr1AbUeN6521tT7HWaZx8J2JJ"

[programs.devnet]
contract = "26KdmFpYTmAauE1JT3sUr1AbUeN6521tT7HWaZx8J2JJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
